server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres
    password: ******
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

parser:
  userAgent: Chrome/4.0.249.0 Safari/532.5
  referrer: https://www.google.com
  configSites:
    -
      name: ******
      url: ******
    -
      name: ******
      url: ******
search:
  maxLemmaFrequency: 100
web-interface :
  path: admin