spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: *******

parser:
  userAgent: Chrome/4.0.249.0 Safari/532.5
  referrer: https://www.google.com
  initSites:
    name1 : http://mukhacheva.ucoz.ru/
    name2 : http://sibuch.ru/
search:
  maxLemmaFrequency: 100
web-interface :
  path: admin