server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine    
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

parser:
  userAgent: Chrome/4.0.249.0 Safari/532.5
  referrer: SiteSearchEngine
  intervalBetweenRequests: 3000
  autoStart : false  
search:
  maxLemmaFrequency: 0
web-interface :
  path: admin
