spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: 895376582

parser:
  userAgent: BelkovSearchBot
  referrer: http://www.google.com
  sites:
    - url: http://www.playback.ru/
      name: Интернет-магазин PlayBack.ru
    - url: https://www.lutherancathedral.ru/
      name: Собор

